const movies = [
  {
    title: 'Jumanji: Następny Poziom',
    id: 1,
    time: 120,
    imageURL:
      'https://media.multikino.pl/thumbnails/50/rc/MzkwNzZG/eyJ0aHVtYm5haWwiOnsic2l6ZSI6WyIxMDAwMCIsIjEwMDAwIl0sIm1vZGUiOiJpbnNldCJ9fQ==/uploads/images/films_and_events/jumanji-nastepny-poziom-pl_df2da630d0.jpg',
    description:
      'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est.',
    tags: ['comedy', 'adventure'],
    seats: [
      { id: 1, available: true },
      { id: 2, available: true },
      { id: 3, available: false },
      { id: 4, available: false },
      { id: 5, available: false },
      { id: 6, available: false },
      { id: 7, available: false },
      { id: 8, available: true },
      { id: 9, available: true },
      { id: 10, available: true },
      { id: 11, available: true },
      { id: 12, available: true },
      { id: 13, available: true },
      { id: 14, available: true },
      { id: 15, available: true },
      { id: 16, available: true },
      { id: 17, available: true },
      { id: 18, available: true },
      { id: 19, available: true },
      { id: 20, available: false },
      { id: 21, available: false },
      { id: 22, available: false },
      { id: 23, available: true },
      { id: 24, available: true },
      { id: 25, available: true },
      { id: 26, available: true },
      { id: 27, available: true },
      { id: 28, available: true },
      { id: 29, available: true },
      { id: 30, available: true },
      { id: 31, available: true },
      { id: 32, available: true },
      { id: 33, available: true },
      { id: 34, available: true },
      { id: 35, available: true },
      { id: 36, available: true },
      { id: 37, available: true },
      { id: 38, available: true },
      { id: 39, available: true },
      { id: 40, available: true },
      { id: 41, available: true },
      { id: 42, available: true },
      { id: 43, available: true },
      { id: 44, available: true },
      { id: 45, available: true },
      { id: 46, available: true },
      { id: 47, available: true },
      { id: 48, available: true },
      { id: 49, available: true },
      { id: 50, available: true },
      { id: 51, available: true },
      { id: 52, available: true },
      { id: 53, available: true },
      { id: 54, available: true },
      { id: 55, available: true },
      { id: 56, available: true },
      { id: 57, available: true },
      { id: 58, available: true },
      { id: 59, available: true },
      { id: 60, available: true },
      { id: 61, available: true },
      { id: 62, available: true },
      { id: 63, available: true },
      { id: 64, available: true }
    ]
  },
  {
    title: 'Czarownica 2',
    id: 2,
    time: 130,
    imageURL: 'https://ssl-gfx.filmweb.pl/po/71/40/747140/7902554.3.jpg',
    description:
      'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est.',
    tags: ['fantasy', 'adventure', 'family'],
    seats: [
      { id: 1, available: true },
      { id: 2, available: true },
      { id: 3, available: true },
      { id: 4, available: true },
      { id: 5, available: false },
      { id: 6, available: false },
      { id: 7, available: false },
      { id: 8, available: false },
      { id: 9, available: false },
      { id: 10, available: false },
      { id: 11, available: false },
      { id: 12, available: false },
      { id: 13, available: false },
      { id: 14, available: false },
      { id: 15, available: false },
      { id: 16, available: false },
      { id: 17, available: false },
      { id: 18, available: false },
      { id: 19, available: false },
      { id: 20, available: true },
      { id: 21, available: true },
      { id: 22, available: true },
      { id: 23, available: true },
      { id: 24, available: true },
      { id: 25, available: true },
      { id: 26, available: true },
      { id: 27, available: true },
      { id: 28, available: true },
      { id: 29, available: true },
      { id: 30, available: true },
      { id: 31, available: true },
      { id: 32, available: true },
      { id: 33, available: true },
      { id: 34, available: true },
      { id: 35, available: true },
      { id: 36, available: true },
      { id: 37, available: true },
      { id: 38, available: true },
      { id: 39, available: true },
      { id: 40, available: true },
      { id: 41, available: true },
      { id: 42, available: true },
      { id: 43, available: true },
      { id: 44, available: true },
      { id: 45, available: true },
      { id: 46, available: true },
      { id: 47, available: true },
      { id: 48, available: true },
      { id: 49, available: true },
      { id: 50, available: true },
      { id: 51, available: true },
      { id: 52, available: true },
      { id: 53, available: true },
      { id: 54, available: true },
      { id: 55, available: true },
      { id: 56, available: true },
      { id: 57, available: true },
      { id: 58, available: true },
      { id: 59, available: true },
      { id: 60, available: true },
      { id: 61, available: true },
      { id: 62, available: true },
      { id: 63, available: true },
      { id: 64, available: true }
    ]
  },
  {
    title: 'Joker',
    id: 3,
    time: 101,
    imageURL:
      'https://images-na.ssl-images-amazon.com/images/I/71YrVzXizzL._AC_SY679_.jpg',
    description:
      'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est.',
    tags: ['drama', 'sci-fic'],
    seats: [
      { id: 1, available: true },
      { id: 2, available: true },
      { id: 3, available: true },
      { id: 4, available: true },
      { id: 5, available: true },
      { id: 6, available: true },
      { id: 7, available: true },
      { id: 8, available: true },
      { id: 9, available: true },
      { id: 10, available: true },
      { id: 11, available: true },
      { id: 12, available: true },
      { id: 13, available: true },
      { id: 14, available: true },
      { id: 15, available: true },
      { id: 16, available: true },
      { id: 17, available: true },
      { id: 18, available: true },
      { id: 19, available: true },
      { id: 20, available: true },
      { id: 21, available: true },
      { id: 22, available: true },
      { id: 23, available: true },
      { id: 24, available: true },
      { id: 25, available: true },
      { id: 26, available: true },
      { id: 27, available: true },
      { id: 28, available: true },
      { id: 29, available: true },
      { id: 30, available: true },
      { id: 31, available: false },
      { id: 32, available: false },
      { id: 33, available: false },
      { id: 34, available: false },
      { id: 35, available: false },
      { id: 36, available: false },
      { id: 37, available: false },
      { id: 38, available: true },
      { id: 39, available: true },
      { id: 40, available: true },
      { id: 41, available: true },
      { id: 42, available: true },
      { id: 43, available: true },
      { id: 44, available: true },
      { id: 45, available: true },
      { id: 46, available: true },
      { id: 47, available: true },
      { id: 48, available: true },
      { id: 49, available: true },
      { id: 50, available: true },
      { id: 51, available: true },
      { id: 52, available: true },
      { id: 53, available: true },
      { id: 54, available: true },
      { id: 55, available: true },
      { id: 56, available: true },
      { id: 57, available: true },
      { id: 58, available: true },
      { id: 59, available: true },
      { id: 60, available: true },
      { id: 61, available: true },
      { id: 62, available: true },
      { id: 63, available: true },
      { id: 64, available: true }
    ]
  },
  {
    title: 'Kod Dedala',
    id: 4,
    time: 95,
    imageURL: 'https://ssl-gfx.filmweb.pl/po/65/44/816544/7905609.3.jpg',
    description:
      'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est.',
    tags: ['criminal'],
    seats: [
      { id: 1, available: true },
      { id: 2, available: true },
      { id: 3, available: true },
      { id: 4, available: true },
      { id: 5, available: true },
      { id: 6, available: true },
      { id: 7, available: true },
      { id: 8, available: true },
      { id: 9, available: true },
      { id: 10, available: true },
      { id: 11, available: true },
      { id: 12, available: true },
      { id: 13, available: true },
      { id: 14, available: true },
      { id: 15, available: true },
      { id: 16, available: true },
      { id: 17, available: true },
      { id: 18, available: true },
      { id: 19, available: true },
      { id: 20, available: true },
      { id: 21, available: true },
      { id: 22, available: true },
      { id: 23, available: true },
      { id: 24, available: true },
      { id: 25, available: true },
      { id: 26, available: true },
      { id: 27, available: true },
      { id: 28, available: true },
      { id: 29, available: true },
      { id: 30, available: true },
      { id: 31, available: true },
      { id: 32, available: true },
      { id: 33, available: true },
      { id: 34, available: true },
      { id: 35, available: true },
      { id: 36, available: true },
      { id: 37, available: true },
      { id: 38, available: false },
      { id: 39, available: false },
      { id: 40, available: false },
      { id: 41, available: false },
      { id: 42, available: false },
      { id: 43, available: false },
      { id: 44, available: false },
      { id: 45, available: false },
      { id: 46, available: false },
      { id: 47, available: true },
      { id: 48, available: true },
      { id: 49, available: true },
      { id: 50, available: true },
      { id: 51, available: true },
      { id: 52, available: true },
      { id: 53, available: true },
      { id: 54, available: true },
      { id: 55, available: true },
      { id: 56, available: true },
      { id: 57, available: false },
      { id: 58, available: false },
      { id: 59, available: false },
      { id: 60, available: true },
      { id: 61, available: true },
      { id: 62, available: true },
      { id: 63, available: true },
      { id: 64, available: true }
    ]
  },
  {
    title: 'Kraina Lodu 2',
    id: 5,
    time: 170,
    imageURL: 'https://ssl-gfx.filmweb.pl/po/67/23/736723/7902555.3.jpg',
    description:
      'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est.',
    tags: ['animation', 'family'],
    seats: [
      { id: 1, available: true },
      { id: 2, available: true },
      { id: 3, available: true },
      { id: 4, available: true },
      { id: 5, available: true },
      { id: 6, available: true },
      { id: 7, available: true },
      { id: 8, available: true },
      { id: 9, available: true },
      { id: 10, available: true },
      { id: 11, available: true },
      { id: 12, available: true },
      { id: 13, available: true },
      { id: 14, available: true },
      { id: 15, available: true },
      { id: 16, available: true },
      { id: 17, available: true },
      { id: 18, available: true },
      { id: 19, available: true },
      { id: 20, available: true },
      { id: 21, available: true },
      { id: 22, available: true },
      { id: 23, available: true },
      { id: 24, available: true },
      { id: 25, available: true },
      { id: 26, available: true },
      { id: 27, available: true },
      { id: 28, available: true },
      { id: 29, available: true },
      { id: 30, available: true },
      { id: 31, available: true },
      { id: 32, available: true },
      { id: 33, available: true },
      { id: 34, available: false },
      { id: 35, available: false },
      { id: 36, available: false },
      { id: 37, available: false },
      { id: 38, available: false },
      { id: 39, available: false },
      { id: 40, available: false },
      { id: 41, available: false },
      { id: 42, available: false },
      { id: 43, available: false },
      { id: 44, available: false },
      { id: 45, available: true },
      { id: 46, available: true },
      { id: 47, available: true },
      { id: 48, available: true },
      { id: 49, available: true },
      { id: 50, available: true },
      { id: 51, available: false },
      { id: 52, available: false },
      { id: 53, available: false },
      { id: 54, available: false },
      { id: 55, available: true },
      { id: 56, available: true },
      { id: 57, available: true },
      { id: 58, available: true },
      { id: 59, available: true },
      { id: 60, available: true },
      { id: 61, available: true },
      { id: 62, available: true },
      { id: 63, available: true },
      { id: 64, available: true }
    ]
  }
];

module.exports = movies;
